name: Code check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    name: npm run lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - run: npm run lint
