name: Code check

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['*']

jobs:
  lint:
    runs-on: ubuntu-latest
    name: pnpm lint
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.1
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - run: pnpm lint
